"""add selected_goals to user

Revision ID: 06ad4f6f1ab2
Revises: f9a9e6779211
Create Date: 2026-05-28 15:10:23.620913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ad4f6f1ab2'
down_revision = 'f9a9e6779211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_goals', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('selected_goals')

    # ### end Alembic commands ###
