"""add checkin model

Revision ID: 545bcb12dcc4
Revises: 06ad4f6f1ab2
Create Date: 2026-05-28 21:31:39.206764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545bcb12dcc4'
down_revision = '06ad4f6f1ab2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_ins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mood_score', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('habits', sa.String(length=200), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='_user_daily_checkin_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('check_ins')
    # ### end Alembic commands ###
