"""add insight snapshots, new db structure

Revision ID: cf3f681ea344
Revises: 99bbfa9f19c9
Create Date: 2026-06-12 17:42:04.715351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf3f681ea344'
down_revision = '99bbfa9f19c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('current_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('checkin_count', sa.Integer(), nullable=True),
    sa.Column('average_mood', sa.Float(), nullable=False),
    sa.Column('top_habits_json', sa.Text(), nullable=True),
    sa.Column('what_we_noticed', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insight_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('checkin_count', sa.Integer(), nullable=True),
    sa.Column('average_mood', sa.Float(), nullable=False),
    sa.Column('top_habits_json', sa.Text(), nullable=True),
    sa.Column('what_we_noticed', sa.Text(), nullable=True),
    sa.Column('goals_snapshot', sa.String(length=200), nullable=True),
    sa.Column('habits_snapshot_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkin_habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checkin_id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['checkin_id'], ['check_ins.id'], ),
    sa.ForeignKeyConstraint(['habit_id'], ['habits.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('premium_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insight_report_id', sa.Integer(), nullable=False),
    sa.Column('reflection_text', sa.Text(), nullable=True),
    sa.Column('reflection_source', sa.String(length=30), nullable=True),
    sa.Column('recommendations_json', sa.Text(), nullable=True),
    sa.Column('recommendation_source', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['insight_report_id'], ['insight_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('weekly_insight')
    with op.batch_alter_table('check_ins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.drop_column('habits')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('onboarding_completed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reflection_tone', sa.String(length=30), nullable=True))
        batch_op.drop_column('theme_preference')
        batch_op.drop_column('ai_consent')
        batch_op.drop_column('selected_habits')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_habits', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ai_consent', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('theme_preference', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('reflection_tone')
        batch_op.drop_column('onboarding_completed')
        batch_op.drop_column('name')

    with op.batch_alter_table('check_ins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('habits', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('created_at')

    op.create_table('weekly_insight',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('average_mood', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('top_habits', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('weekly_insight_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('weekly_insight_pkey'))
    )
    op.drop_table('premium_insights')
    op.drop_table('checkin_habits')
    op.drop_table('user_habits')
    op.drop_table('insight_reports')
    op.drop_table('current_insights')
    op.drop_table('habits')
    # ### end Alembic commands ###
